enum UploadEvent {
  init,
  onTapFile,
  onLoading,
  onAddData,
  onWideArea,
  onTapSave,
  onDoneToast,
  onSearch,
  onTapArea,
  onClearMessage,
  onChangedArea,
  onChangedDivision,
  onChangedPassword,
  onChangedWide,
  onChangedAddData, onPreviousScreen,
}
