enum MainEvent {
  init,
  onTapType,
  onDelete,
  onSearch,
  onTapDrawer,
  onTapItemAll,
  onTapItemRemove,
  onTapItem,
  isLoading,
  onTapRefresh,
  onTapMenu,
  onTapItemWithShift,
  onTapUpload,
  onTapShiftKey,
  onShowDialog,
  onTapNoticePage,
  onLogout, onPassword,
}
